name = "hotgone"
main = "functions/api/[[route]].ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && npm run build"
cwd = "."
watch_dir = "frontend/src"

[[kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[vars]
NODE_ENV = "production"

[env.production.vars]
API_URL = "https://hotgone.pages.dev"

[env.preview.vars]
API_URL = "https://preview.hotgone.pages.dev"