name = "hotgone"
compatibility_date = "2024-08-03"
pages_build_output_dir = "frontend/dist"

# Cloudflare Pages 配置
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"

# 环境变量 (通过 Cloudflare Dashboard 设置)
# DATABASE_URL - Neon PostgreSQL 连接字符串
# PORT - API 端口 (默认 3001)

# Functions 路由配置
[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

# 页面路由配置 - SPA 支持
[[redirects]]
from = "/*"
to = "/index.html"
status = 200